    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.servicename.entrypoints=https"
      - "traefik.http.routers.servicename.rule=(Host(`portainer.example.io`))"
      - "traefik.http.routers.servicename.tls=true"
      - "traefik.http.routers.servicename.tls.certresolver=cloudflare"
      # Loadbalancer Port ist dafür zuständig das du den Port 9000 von Portainer durchschleifst weil dort der Webserver läuft.
      - "traefik.http.services.servicename.loadbalancer.server.port=9000"
      - "traefik.http.routers.servicename.middlewares=default@file"
