    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.rule=(Host(`portainer.example.io`))"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
      # Loadbalancer Port ist dafür zuständig das du den Port 9000 von Portainer durchschleifst weil dort der Webserver läuft.
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.portainer.middlewares=default@file"
